name: PHP Composer

on:
  push:
    branches: [ config ]
  pull_request:
    branches: [ config ]

jobs:
  build:
      strategy:
        matrix:
          php: ['5.6']
          os: ['ubuntu-16.04']
          include:
            - php: '5.6'
              os: 'ubuntu-16.04'
    
      runs-on: ${{ matrix.os }}
      env:
          PHP_VERSION: ${{ matrix.php }}
      steps:

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run-script test
